class Constants:

    LANGUAGE_SOURCE = 'lang_src'
    LANGUAGE_TARGET = 'lang_tgt'
    DATASET_NAME = 'opus_books'
    INPUT_ENCODER = 'encoder_input'
    INPUT_DECODER = 'decoder_input'
    LABEL = 'label'
    MASK_ENCODER = 'encoder_mask'
    MASK_DECODER = 'decoder_mask'
    SEQUENCE_LENGTH = 'sequence_length'
    TOKEN_UNKNOWN = '[UNK]'
    TOKEN_PADDING = '[PAD]'
    TOKEN_START_OF_SENTENCE = '[SOS]'
    TOKEN_END_OF_SENTENCE = '[EOS]'
    TOKENIZER_FILE = 'tokenizer_file'
    TRAIN = 'train'
    TRANSLATION = 'translation'
    TEXT_SOURCE = 'text_source'
    TEXT_TARGET = 'text_target'